apiVersion: batch/v1
kind: CronJob
metadata:
  name: myip
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: myip
            image: curlimages/curl
            command:
            - /bin/sh
            - -c
            - date; curl -s ipinfo.io/ip
